[tool.poetry]
name = "aganitha-cli"
version = "0.1.0"
description = "CLI tool for fetching PubMed papers"
authors = [
    {name = "Shreya"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = "requires-python = ">=3.11,<4.0"
dependencies = [
    "biopython (>=1.85,<2.0)",
    "click (>=8.2.1,<9.0.0)",
    "pandas (>=2.3.1,<3.0.0)",
    "tqdm (>=4.67.1,<5.0.0)",
]
[tool.poetry.scripts]
pubmed = "cli:cli"

packages = []
